### ISSUE TITLE
Fisher no where to be found?

### ISSUE THREAD

**Issue by FirefighterKyle** [Rav3n95/gp-traders#1]
So at first I tried to enable the blip for the fisher which did nothing (yes I restarted the script) I turned it back off and teleported to all the vectors and he was not at any location the Hunter is good up in Paleto but the fisher is no where to be found?

**Comment by Rav3n95** [comment]
Could be your dlc version, since I'm using ped from last dlc. Try to change the model

**Comment by FirefighterKyle** [comment]
Wait, so if I have a higher DLC version, older models / DLC version won't work? 

I will try to play around with the model, I am trying to learn about the GameBuild command and how to allow higher DLC versions.

**Comment by FirefighterKyle** [comment]
Also, where do you find your ped models at? I am looking at the CFX page and I don't see ig_vernon on the list at all.
